version: '3.8'

services:
  cart-db:
    image: mysql:8.4
    container_name: cart-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_cart
    ports:
      - "3307:3306"
    volumes:
      - ./db/cart_init.sql:/docker-entrypoint-initdb.d/init.sql
      - cart-db-data:/var/lib/mysql
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  cart-service:
    build: .
    container_name: cart-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cart-db:3306/ecommerce_cart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: mysecretkeymysecretkeymysecretkey12345
    depends_on:
      cart-db:
        condition: service_healthy
    networks:
      - ecommerce-network

volumes:
  cart-db-data:

networks:
  ecommerce-network:
    driver: bridge
