FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app
COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY --from=builder /app/target/cart-service-0.0.1-SNAPSHOT.jar cart-service.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "cart-service.jar"]
